[build]
builder = "nixpacks"
buildCommand = "cd chatbot-backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd chatbot-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "always"

[env]
PYTHON_VERSION = "3.9"
